name: Update

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

jobs:
  update_run_count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get Run Count
        id: get_run_count
        run: |
          import requests
          API_KEY = "${{ secrets.API_KEY }}"
          response = requests.get("https://run.iokun.cn/get_run_count/total", headers={"X-API-KEY": API_KEY})
          run_count = response.json()["total_run_count"]
          print(f"total_run_count={run_count}", file=open("run_count.txt", "a"))
        shell: python

      - name: Update README
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            let readme = '';
            if (fs.existsSync('README.md')) {
              readme = fs.readFileSync('README.md', 'utf8');
            }
            const runCountString = `**脚本总计** Run Count: ${{ env.total_run_count }}`;
            const runCountRegex = /\*\*脚本总计\*\* Run Count: \d+/;
            if (readme.match(runCountRegex)) {
              readme = readme.replace(runCountRegex, runCountString);
            } else if (readme.includes('**脚本总计**')) {
              readme = readme.replace('**脚本总计**', runCountString);
            } else {
              readme += `\n${runCountString}`;
            }
            fs.writeFileSync('README.md', readme);
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Add changes to git
        run: |
          git add run_count.txt
          git add README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "feat: update run count in README"
          git push
