name: Update README Run Count

on:
  workflow_dispatch:

jobs:
  update_run_count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get Run Count
        id: get_run_count
        run: |
          import requests
          API_KEY = "${{ secrets.API_KEY }}"
          response = requests.get("https://run.iokun.cn/get_run_count/total", headers={"X-API-KEY": API_KEY})
          run_count = response.json()["total_run_count"]
          print(f"::set-output name=total_run_count::{run_count}")
        shell: python

      - name: Update README
        uses: fxcoudert/update-readme-action@v1.0.0
        with:
          file: README.md
          regex: "Run Count: "
          replacement: "Run Count: ${{ steps.get_run_count.outputs.total_run_count }}"
          commit-message: "feat: update run count in README"
          author-name: GitHub Actions
          author-email: actions@github.com
