name: Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:
  repository_dispatch:
    types: server-update

jobs:
  update_run_count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get and Check Run Count
        id: get_check_run_count
        run: |
          import requests
          API_KEY = "${{ secrets.API_KEY }}"
          response = requests.get("https://run.iokun.cn/get_run_count/total", headers={"X-API-KEY": API_KEY})
          run_count = response.json()["total_run_count"]
          print(f"total_run_count={run_count}", file=open("run_count.txt", "a"))
        shell: python

      - name: Check if Run Count has increased
        run: |
          if [ $((cat run_count.txt | tail -1 | cut -d'=' -f2)) -gt $((cat run_count.txt | tail -2 | head -1 | cut -d'=' -f2)) ]; then
            echo "skip=false" >> $GITHUB_ENV
            echo "total_run_count=$CURR_RUN_COUNT" >> $GITHUB_ENV
          fi

      - name: Update README and Push Changes
        if: env.skip == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let readme = '';
            if (fs.existsSync('README.md')) {
              readme = fs.readFileSync('README.md', 'utf8');
            }
            const runCountString = `**脚本运行总计：** ${{ env.total_run_count }}`;
            const runCountRegex = /\*\*脚本运行总计：\*\* \d+/;
            if (readme.match(runCountRegex)) {
              readme = readme.replace(runCountRegex, runCountString);
            } else if (readme.includes('**脚本运行总计：**')) {
              readme = readme.replace('**脚本运行总计：**', runCountString);
            } else {
              readme += `\n${runCountString}`;
            }
            fs.writeFileSync('README.md', readme);
            git add run_count.txt
            git add README.md
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git commit -am "feat: update run count in README"
            git push
          github-token: ${{ secrets.GH_TOKEN }}
