name: Update

on:
  workflow_dispatch:

jobs:
  update_run_count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get Run Count
        id: get_run_count
        run: |
          import requests
          API_KEY = "${{ secrets.API_KEY }}"
          response = requests.get("https://run.iokun.cn/get_run_count/total", headers={"X-API-KEY": API_KEY})
          run_count = response.json()["total_run_count"]
          print(f"::set-output name=total_run_count::{run_count}")
        shell: python

      - name: Update README
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            let readme = '';
            if (fs.existsSync('README.md')) {
              readme = fs.readFileSync('README.md', 'utf8');
            }
            readme = readme.replace(/Run Count: \d+/, `Run Count: ${{ steps.get_run_count.outputs.total_run_count }}`);
            if (!readme.includes('Run Count:')) {
              readme += `\nRun Count: ${{ steps.get_run_count.outputs.total_run_count }}`;
            }
            fs.writeFileSync('README.md', readme);
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "feat: update run count in README"
          git push
